const SUPABASE_URL="https://ekaiaxmqxrqqnhwwkbbs.supabase.co";
const SUPABASE_KEY="sb_publishable_4TBx_W1TGS_EFjXpBnv01g_Qgly5rEn";
const cloud=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let cloudUser=null,cloudAccess="trial",cloudPlanCount=0;
const authGate=$("authGate"),loginMessage=$("loginMessage");
function loginNotice(message,error=false){loginMessage.textContent=message;loginMessage.className="login-message show"+(error?" error":"")}
async function ensureProfile(user){await cloud.from("teacher_profiles").upsert({id:user.id,full_name:user.user_metadata?.full_name||"",school_name:user.user_metadata?.school_name||""},{onConflict:"id",ignoreDuplicates:true})}
async function setSession(session){cloudUser=session?.user||null;authGate.hidden=!!cloudUser;$("accountBtn").hidden=!cloudUser;$("topSignOutBtn").hidden=!cloudUser;$("accessBadge").hidden=!cloudUser;if(cloudUser){await ensureProfile(cloudUser);const {data:access}=await cloud.from("access_controls").select("access_level,approved_at").maybeSingle();cloudAccess=access?.access_level||"trial";$("teacherEmail").textContent=cloudUser.email;$("accountEmail").textContent=cloudUser.email;$("teacherName").textContent=cloudUser.user_metadata?.full_name||"Docente MEDUCA";updateAccessUI();document.querySelector(".status").classList.add("cloud-badge");document.querySelector(".status").innerHTML="<i></i> Guardado permanente";await migrateLocalPlans()}}
function updateAccessUI(){const full=cloudAccess==="full",badge=$("accessBadge"),box=$("accountAccess");badge.textContent=full?"ACCESO COMPLETO":`PRUEBA · ${Math.max(0,1-cloudPlanCount)} PLAN DISPONIBLE`;badge.classList.toggle("full",full);if(box)box.innerHTML=full?'<b>✓ Acceso completo aprobado</b><span>Puede crear y guardar planificaciones sin límite.</span>':'<b>Acceso de prueba</b><span>Puede explorar la plataforma y crear una planificación. El administrador debe aprobar el acceso completo.</span>'}
let authMode="login";
function setAuthMode(mode){authMode=mode;const signup=mode==="signup";$("signupFields").hidden=!signup;$("signupConfirmLabel").hidden=!signup;$("signupName").required=signup;$("signupSchool").required=signup;$("signupConfirm").required=signup;$("loginPassword").autocomplete=signup?"new-password":"current-password";$("showLoginBtn").classList.toggle("active",!signup);$("showSignupBtn").classList.toggle("active",signup);$("showLoginBtn").setAttribute("aria-selected",String(!signup));$("showSignupBtn").setAttribute("aria-selected",String(signup));$("authTitle").textContent=signup?"Cree su cuenta docente":"Bienvenido a su espacio de planificación";$("authIntro").textContent=signup?"Regístrese gratuitamente para guardar sus planificaciones y acceder desde cualquier dispositivo.":"Ingrese con su correo y contraseña.";$("loginBtn").textContent=signup?"Crear mi cuenta":"Iniciar sesión";$("resetPasswordBtn").hidden=signup;$("accountHint").innerHTML=signup?'¿Ya tiene una cuenta? Seleccione <b>Iniciar sesión</b>.':'¿Es su primera vez? Seleccione <b>Crear cuenta</b>.';loginMessage.className="login-message";loginMessage.textContent=""}
$("showLoginBtn").onclick=()=>setAuthMode("login");$("showSignupBtn").onclick=()=>setAuthMode("signup");
$("loginForm").onsubmit=async e=>{e.preventDefault();const email=$("loginEmail").value.trim().toLowerCase(),password=$("loginPassword").value,signup=authMode==="signup";if(signup&&password!==$("signupConfirm").value)return loginNotice("Las contraseñas no coinciden.",true);$("loginBtn").disabled=true;$("loginBtn").textContent=signup?"Creando cuenta…":"Ingresando…";const result=signup?await cloud.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname,data:{full_name:$("signupName").value.trim(),school_name:$("signupSchool").value.trim()}}}):await cloud.auth.signInWithPassword({email,password});$("loginBtn").disabled=false;$("loginBtn").textContent=signup?"Crear mi cuenta":"Iniciar sesión";if(result.error)return loginNotice(signup?"No fue posible crear la cuenta. Revise los datos o pruebe con otro correo.":"Correo o contraseña incorrectos.",true);if(signup&&!result.data.session){$("loginForm").reset();return loginNotice("Cuenta creada. Revise su correo y confirme el registro antes de iniciar sesión.")}loginNotice(signup?"Cuenta creada. Abriendo su espacio docente…":"Acceso correcto. Abriendo su espacio docente…")};
$("resetPasswordBtn").onclick=async()=>{const email=$("loginEmail").value.trim().toLowerCase();if(!email)return loginNotice("Escriba primero su correo electrónico.",true);$("resetPasswordBtn").disabled=true;const {error}=await cloud.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});$("resetPasswordBtn").disabled=false;if(error)return loginNotice("No se pudo enviar el enlace de recuperación. Inténtelo nuevamente.",true);loginNotice("Si el correo está autorizado, recibirá un enlace para crear una nueva contraseña.")};
function passwordNotice(message,error=false){const el=$("passwordMessage");el.textContent=message;el.className="login-message show"+(error?" error":"")}
$("passwordForm").onsubmit=async e=>{e.preventDefault();const password=$("newPassword").value,confirmation=$("confirmPassword").value;if(password!==confirmation)return passwordNotice("Las contraseñas no coinciden.",true);if(password.length<8)return passwordNotice("Use al menos 8 caracteres.",true);$("passwordBtn").disabled=true;$("passwordBtn").textContent="Guardando…";const {error}=await cloud.auth.updateUser({password});$("passwordBtn").disabled=false;$("passwordBtn").textContent="Guardar contraseña";if(error)return passwordNotice("No se pudo guardar la contraseña. Pruebe una combinación más segura.",true);$("passwordForm").reset();passwordNotice("Contraseña guardada. Ya puede iniciar sesión con su correo y contraseña.")};
$("accountBtn").onclick=()=>$("accountDialog").showModal();async function signOut(){const {error}=await cloud.auth.signOut();if(error)return toast("No se pudo cerrar la sesión. Inténtelo nuevamente.");if($("accountDialog").open)$("accountDialog").close();location.reload()}$("signOutBtn").onclick=signOut;$("topSignOutBtn").onclick=signOut;
async function saveCloud(record){if(!cloudUser)throw new Error("Debe iniciar sesión.");const {error}=await cloud.from("plans").insert({user_id:cloudUser.id,plan_type:record.plan_type,title:record.title,grade:record.grade||"",scenario:record.scenario||"",theme:record.theme||"",content:record.content});if(error)throw error}
async function migrateLocalPlans(){const migrationKey="meducaCloudMigrated_"+cloudUser.id;if(localStorage.getItem(migrationKey)==="yes")return;const local=saved();for(const p of local){await saveCloud({plan_type:"daily",title:p.theme||"Daily Lesson Plan",grade:p.grade,scenario:p.scenario,theme:p.theme,content:p})}const packs=JSON.parse(localStorage.getItem("meducaThemePacks")||"[]");for(const p of packs){await saveCloud({plan_type:"theme_pack",title:p.theme||"Theme Planner",grade:p.grade,scenario:p.scenario,theme:p.theme,content:p})}localStorage.setItem(migrationKey,"yes")}
$("saveBtn").onclick=async()=>{if(!currentPlan)return toast("Primero genere una planificación.");try{await saveCloud({plan_type:"daily",title:lessonTitle(currentPlan),grade:currentPlan.grade,scenario:currentPlan.scenario,theme:currentPlan.theme,content:{...currentPlan,objective:$("editableObjective").innerText.trim(),body:getEditedBody()}});toast("Planificación guardada permanentemente.");updateCountCloud()}catch(e){toast(String(e?.message||"").includes("TRIAL_PLAN_LIMIT")?"Ya utilizó su planificación de prueba. Solicite la aprobación del acceso completo.":"No se pudo guardar. Revise su conexión.")}};
async function updateCountCloud(){if(!cloudUser)return;const {count}=await cloud.from("plans").select("id",{count:"exact",head:true});cloudPlanCount=count||0;$("savedCount").textContent=cloudPlanCount;updateAccessUI()}
function safeText(value){return String(value||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function showCloudSaved(){const {data,error}=await cloud.from("plans").select("id,title,grade,scenario,theme,plan_type,content,updated_at").order("updated_at",{ascending:false});if(error)return toast("No se pudo abrir la biblioteca.");$("savedList").innerHTML=data.length?data.map(p=>`<div class="saved-item"><div><b>${safeText(p.title)}</b><small>${safeText(p.grade)} · ${safeText(p.scenario)} · ${new Date(p.updated_at).toLocaleDateString("es-PA")}</small></div><button data-cloud-id="${p.id}">Abrir</button></div>`).join(""):`<p>Su biblioteca permanente está vacía.</p>`;$("savedDialog").showModal();$("savedList").onclick=e=>{const p=data.find(x=>x.id===e.target.dataset.cloudId);if(!p)return;if(p.plan_type==="daily"){currentPlan=p.content;render(currentPlan,currentPlan.body);$("savedDialog").close();toast("Planificación recuperada de su cuenta.")}else if(p.plan_type==="theme_pack"&&p.content?.html){$("engineOutput").innerHTML=`<div class="engine-toolbar"><div><b>Paquete recuperado</b><br><small>${safeText(p.grade)} · ${safeText(p.scenario)}</small></div><div class="engine-actions"><button id="engineSave">Guardar copia</button><button id="engineWord">Word</button><button id="enginePrint">PDF</button></div></div><div id="engineDocument" class="engine-sheet">${p.content.html}</div>`;$("engineEmpty").classList.add("hidden");$("engineOutput").classList.remove("hidden");$("savedDialog").close();$("engineDialog").showModal();bindEngine(p.content);showEngineLesson(0);toast("Paquete recuperado de su cuenta.")}}}
$("savedNav").onclick=showCloudSaved;
const bindEngineLocal=bindEngine;bindEngine=function(d){bindEngineLocal(d);$("engineSave").onclick=async()=>{try{await saveCloud({plan_type:"theme_pack",title:d.theme+" · Theme Planner",grade:d.grade,scenario:d.scenario,theme:d.theme,content:{...d,html:$("engineDocument").innerHTML}});toast("Paquete completo guardado permanentemente.");updateCountCloud()}catch(e){toast("No se pudo guardar el paquete.")}}};
function requireFullAccess(e){if(cloudAccess==="full")return;e.preventDefault();e.stopImmediatePropagation();toast("Esta función se activa cuando el administrador aprueba su acceso completo.")}
$("engineForm").addEventListener("submit",requireFullAccess,true);$("quarterForm").addEventListener("submit",requireFullAccess,true);
$("plannerForm").addEventListener("submit",e=>{if(cloudAccess!=="full"&&cloudPlanCount>=1){e.preventDefault();e.stopImmediatePropagation();toast("Ya utilizó su planificación de prueba. Solicite el acceso completo.")}},true);
cloud.auth.onAuthStateChange((event,session)=>setTimeout(async()=>{await setSession(session);await updateCountCloud();if(event==="PASSWORD_RECOVERY"&&session){$("accountDialog").showModal();passwordNotice("Escriba y confirme su nueva contraseña.");$("newPassword").focus()}},0));cloud.auth.getSession().then(({data})=>setSession(data.session).then(updateCountCloud));
