const MEDUCA_CURRICULUM={
"Pre-Kinder":{cefr:"Pre-A1.1",scenarios:[
["Meeting New Friends","Meeting My Friends","Saying Please and Thank You"],["Exploring Our Classroom","Things in My Classroom","Colors in My Classroom"],["Me and My Family","This Is Me!","My Family"],["Let's Eat!","I Love Fruit!","I Eat Vegetables!"],["Numbers Around Me","Let's Count to Five!","How Many?"],["Fun with Letters","The A-B-Cs","Apple, Banana, Coconut"],["Inside My School!","My Teacher!","Time for Recess!"],["Panama's Plants and Animals","It's a Plant.","It's an Animal."]]},
"Kindergarten":{cefr:"Pre-A1.2",scenarios:[
["It's a School Day!","Let's Listen!","Stand Up!"],["Our Routines","First, I Sit Down.","Pick It Up!"],["Hold Up Ten Fingers!","I Can Count!","All the Pencils!"],["Where Is It?","Where Is Your Book?","Go to the Window."],["What's that Sound?","The Cat Says \"Meow\".","That's a Rooster!"],["Let's Dance!","Move Around","One Step In, Two Steps Out!"],["I'm Happy.","I'm Excited!","How Are You?"],["I Like School!","I Like Games!","I Like Math!"]]},
"1st Grade":{cefr:"Pre-A1.3",scenarios:[
["All Week Long!","Today Is Tuesday!","It's the Weekend."],["Nice Weather Today!","It's Sunny!","It's Raining."],["Colors in Our World","That's a Purple Flower.","It's an Orange Cat."],["My Family and I","It's My Family!","She Is My Mom!"],["Colors of Things that Go","That's a Blue Bus.","That's a Red Bike."],["Shapes Around Us","I See a Rectangle.","That Is a Circle."],["Shapes on Our Plates","It's a Square Cracker.","It's a Round Orange."],["It's Our Garden.","The Pink Flowers!","A Tall Tree!"]]},
"2nd Grade":{cefr:"Pre-A1.4",scenarios:[
["School Days","Yesterday Was Wednesday.","Today Is Friday!"],["School Life Adventures","That's a Big Book!","That's a Small, Brown Bag."],["All About the Weather","A Perfect Day!","Dress for the Weather."],["All About My Body","Head to Toes!","Hats and Shoes!"],["Exploring My Community","It's the Park!","It's the Market!"],["Discovering Nature's Wonders","It's the Rainforest.","It's a Slow, Furry Sloth!"],["Fun Outdoors!","I Love to Run!","I Like to Swim."],["It's Festival Season.","Look at the Fireworks!","Food I Eat During a Celebration"]]},
"3rd Grade":{cefr:"A1.1",scenarios:[
["Places I Can Go","I'm at School.","I'm at the Market."],["A Polite Request","Can I Have a Pencil?","Sorry, I Can't Help You."],["Discovering Our Classroom","What's in Your Bag?","The Book Is on the Table."],["This Beautiful Day","It's Sunny. I'm Happy!","It's Raining! I Need an Umbrella."],["Let's Go Shopping!","One, Two, Three Bananas!","I Want Five Pineapples."],["I Can Connect with Nature!","I Can Relax and Listen.","I'm Outside. I'm Happy!"],["It's Time to Eat.","What's Your Favorite Food?","I Like Sancocho!"],["My Evening Routine","First, I Brush My Teeth.","I'm Sleepy. It's Bedtime."]]},
"4th Grade":{cefr:"A1.2",scenarios:[
["A Walk in the Neighborhood","This Is My Favorite.","It's the Best!"],["Helping in the Garden","The Tomatoes Grow Quickly.","These Plants Are from Panama."],["Shopping at the Market","How Much Is the Pineapple?","I Need Five Yucas."],["Visiting the Panama Canal","The Vessels Are Big Because...","A Vessel Is Crossing!"],["A Trip to the Beach","Let's Pack for a Trip.","I Always Pack Lunch."],["It's the Rainy Season","Where's the Puddle?","I Need an Umbrella."],["The Beautiful Mola","A Mola Has Many Colors!","I Can Make a Mola."],["Our Traditional Style of Dress","She Is Wearing a Pollera.","Let's Dress for a Dance."]]},
"5th Grade":{cefr:"A1.3",scenarios:[
["Following Instructions at School","First, I Cut the Paper.","Let's Make a Poster!"],["Taking Care of Our Class","We Are Sweeping the Floors.","Let's Arrange the Chairs."],["The Local Farm Stand","I Need Two Papayas, Please.","How Much Are the Bananas?"],["Helping Around the House","I Wash the Dishes Every Day.","We All Do Chores."],["Time for Exercise","I Like Walking in the Afternoon.","We Can Swim."],["Recycling for Our World","We Recycle Plastic Bottles Every Day.","Composting Is Easy."],["Conservation: Morning, Noon, and Night!","Let's Get Cool in the Shade.","Turn Off the Lights, Please."],["Planning Meals for My Family","Fruits and Vegetables Are Good for You.","Panama Has Delicious Food!"]]},
"6th Grade":{cefr:"A2.1",scenarios:[
["Our Community News","Reporting From the School!","Our Community Is Famous For..."],["Keeping Our Communities Clean","We Should Clean the Classroom on Friday.","Who Will Bring the Cleaning Supplies?"],["In the Library","I Need a Lot of Books!","How Do I Find a Book in the Library?"],["Our Classroom News","I Will Write the Article About Our School Trip.","We Need Pictures for the Classroom Newsletter."],["Our Amazing Community","This Is My Amazing Community.","This School Has Been Here a Long Time!"],["An Environmental Project","Let's Recycle Our Paper!","How Can We Help the Environment?"],["Our Weather Report","Today's Weather Will Be Sunny with Some Rain Later.","How Will the Weather Change Tomorrow?"],["The Talents Around Us","Who Will Perform in the Fiestas Patrias Activities?","I Will Play the Drums in the Parade."]]}
};
